public class Address {
    public void homeaddress(){

        //1
        String yn='Elyas Sadat';
        system.debug('My Name Is :' + yn);

        //2
        Integer tn=13;
        system.debug('Total number of members in my family :'+ tn);

        //3
        string hn='Etehad wa Mohabat';
        system.debug('House Name:' + hn);

        //4
        integer hnum=1;
        system.debug('House Number :' + hnum);

        //5
        string stn='Khelwaty';
        system.debug('Street Name:' + stn);

        //6
        string cin='Jowzjan';
        system.debug('City Name:' + cin);
        
        //7
        string stateN='North';
        System.debug('State Name:' + stateN);

        //8
        Integer statecode=1124;
        system.debug('State ISO Code: ' + statecode);

        //9
        string CountryName='Afghanistan';
        system.debug('Country Name: ' + CountryName);

        //10
        Integer countrycode=123;
        system.debug('Country Code: '+ countrycode);

        //11
        Integer ZipC0de=777;
        System.debug('ZipCode :' + ZipC0de);

        //12
        Boolean homeyn= True;
        system.debug('Is this your current home or not :' + homeyn);

    }
}