public class OperationsHelper {

    public decimal smallestOutOfThreeNumbers(decimal a, decimal b, decimal c){
        decimal result1 = 0;
        if((a<b) && (a<c)){
            result1 = a;
        }else if((b<a) && (b<c)){
            result1 = b;
        }else if((c<a) && (c<b)){
            result1 =c;
        }return result1;
    }
    public Integer sumOfPositiveintegers(Integer n){
        integer sum;
        if (n<0) {
            sum = null;
            system.debug('we are not calculating the sum for negative numbers');
            
        }
        else {
            sum = 0;
            for (Integer
        }
    }
}

